Repository luciferreeves/blaver, pull requests merged in 2022-01, with the labels that each got.

#7 Updated generateSet file
  examples/node/generateSet.js
Labels: refactor

#6 Fix locale files
  locale/ReadMe.md
  locale/af_ZA.js
  locale/ar.js
  locale/az.js
  locale/cz.js
  locale/de.js
  locale/de_AT.js
  locale/de_CH.js
  locale/el.js
  locale/en.js
  locale/en_AU.js
  locale/en_AU_ocker.js
  locale/en_BORK.js
  locale/en_CA.js
  locale/en_GB.js
  locale/en_GH.js
  locale/en_IE.js
  locale/en_IND.js
  locale/en_NG.js
  locale/en_US.js
  locale/en_ZA.js
  locale/es.js
  locale/es_MX.js
  locale/fa.js
  locale/fi.js
  locale/fr.js
  locale/fr_CA.js
  locale/fr_CH.js
  locale/ge.js
  locale/he.js
  locale/hr.js
  locale/hy.js
  locale/id_ID.js
  locale/it.js
  locale/ja.js
  locale/ko.js
  locale/nb_NO.js
  locale/ne.js
  locale/nl.js
  locale/nl_BE.js
  locale/pl.js
  locale/pt_BR.js
  locale/pt_PT.js
  locale/ro.js
  locale/ru.js
  locale/sk.js
  locale/sv.js
  locale/tr.js
  locale/uk.js
  locale/ur.js
  locale/vi.js
  locale/zh_CN.js
  locale/zh_TW.js
  locale/zu_ZA.js
Labels: fix, refactor

#10 Update to run Build workflow on all branches
  .github/workflows/main.yml
Labels: enhancement, refactor

#14 Chore: Update type definitions for bigInt() in index.d.ts
  index.d.ts
Labels: fix, refactor

#15 Removed unneeded this assignment to self
  lib/animal.js
  lib/commerce.js
  lib/database.js
  lib/date.js
  lib/finance.js
  lib/git.js
  lib/image.js
  lib/lorem.js
  lib/music.js
  lib/phone_number.js
  lib/time.js
  lib/vehicle.js
  lib/word.js
Labels: refactor

#20 Update issue templates
  .github/ISSUE_TEMPLATE/---blank-issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  docs/CNAME
Labels: enhancement, refactor
